name: Saludo usando variables
on:
  workflow_dispatch:
env:
  DIA_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludo
        run: echo ${{ env.SALUDO }} ${{ env.SALUDO }}  hoy es ${{ env.DIA_SEMANA }}
  saludo-secretos:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo
        run: echo ${{ env.SALUDO }}  ${{ env.SALUDO }} mi contraseña es ${{ secrets.CONTRASENA }}
